version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:stretch
    working_directory: /go/src/github.com/qlik-oss/kustomize-plugins
    steps:
      - checkout
      - run:
          name: "Verify build"
          command: |
            make
workflows:
  version: 2
  commit:
    jobs:
      - build
